=== christgau/sps/schema/progression_system.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://sports.s14u.de/racingmode.schema.json",
    "title": "progression system",
    "description": "A progression system describes how competitors, i.e. crews, teams, individual athletes, in a sport event (aka 'discipline') move from phase to phase (aka 'rounds'). Such a description also allows to derive the number and types of units (aka 'races' or 'heats') for a given phase.",
    "type": "object",
    "properties": {
        "title": {
            "type": "string",
            "description": "The name of the system as it is commonly referred to, e.g. in rules."
        },
        "sport": {
            "type": "string",
            "description": "The name of the sport to which the system applies to. Recognized standard names of the sport should be used."
        },
        "description": {
            "type": "string",
            "description": "A more detailed description, e.g., when to use this system."
        },
        "version": {
            "type": "string",
            "description": "Some kind of version number."
        },
        "capacity": {
            "type": "integer",
            "description": "Regular number of lanes or starting positions for that progression system, e.g. nine for athletics"
        },
        "authors": {
            "type": "array",
            "description": "List of peoples (with optional e-mail address), e.g. John Doe <john.doe@example.com>",
            "items": { 
                "type": "string"
            },
            "uniqueItems": true
        },
        "ranges": {
            "type": "array",
            "items": { "$ref": "#/$defs/range" }
        }
    },
    "required": ["title", "sport", "ranges"],
    "$defs": {
        "range": {
            "description": "The progression system may depend on the number of competitors which are expressed with multiple ranges inside the document.",
            "type": "object",
            "properties": {
                "from": {
                    "type": "integer",
                    "minimum": 1,
                    "description": "Inclusive starting value from which on the range applies."
                },
                "to": {
                    "type": "integer",
                    "minimum": 1,
                    "description": "Inclusive starting value from which on the range applies."
                },
                "phases": {
                    "type": "array",
                    "items": { "$ref": "#/$defs/phase" },
                    "minItems": 1
                }
            },
            "required": [ "from" ]
        },
        "phase": {
            "description": "A phase is a stage or round in a sport event. There might be a qualification and final, or there might be heats, semi-finals, finals and so on.",
            "type": "object",
            "properties": {
                "label": {
                    "type": "string",
                    "description": "A human-readable name of the phase, like 'Qualification', 'Round of 32', or 'Quarterfinals'."
                },
                "code": {
                    "type": "string",
                    "description": "An identifier value that makes sense in some other system, e.g. in RCS it might be 'FNL' (padding '-' removed) for the 'Finals' round."
                },
                "order": {
                    "type": "integer",
                    "description": "A value that might be used for sorting the phases. If no value is supplied, the phases should be considered in their appearance order where finals should come last."
                },
                "units": {
                    "type": "array",
                    "items": { "$ref": "#/$defs/unit" },
                    "minItems": 1
                }
            },
            "required": [ "label", "code", "units" ]
        },
        "unit": {
            "description": "A fraction of a phase, e.g. an individual heat of the qualification round, or one of two semifinals",
            "type": "object",
            "properties": {
                "label": {
                    "type": "string",
                    "description": "The long description of the unit, e.g. 'Heat 1' or 'Final B'."
                },
                "code": {
                    "type": "string",
                    "description": "The short description of the unit, e.g. 'H1' or 'FB'. It must be unique among all units to be used as a reference in the rules"
                },
                "order": {
                    "type": "integer",
                    "description": "A value to sort the different units. If no order is provided, the order should be determined from the order of appearance."
                },
                "ruleTexts": {
                    "type": "object",
                    "description": "A short and long textual summary of the qualification rules, e.g. '1-4 to Final A, Remainers to Final B' and '1-4 -> FA, 5-... -> FB'.",
                    "properties": {
                        "short": { "type": "string" },
                        "long": { "type": "string" }
                    }
                },
                "rules": {
                    "type": "array",
                    "description": "A list of rules which specify which competitors from other (or the same) round qualify for the unit.",
                    "items": { "$ref": "#/$defs/rule" }
                },
                "subunits": {
                    "type": "array",
                    "items": { "$ref": "#/$defs/subunit" }
                }
            },
            "required": [ "label", "code" ]
        },
        "subunit": {
            "type": "object",
            "description": "Further distinction within a unit, like one of several matches for same pair of teams (play-offs)",
            "properties": {
                "label": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                }
            }
        },
        "rule": {
            "type": "object",
            "description": "A single rule that specifies the progression of one or multiple competitors from a phase and possibly unit (pull approach).",
            "properties": {
                "option": {
                    "type": "integer",
                    "description": "Multiple variants of a ruleset might be supplied, which are distinguished by their option number",
                    "default": 0
                },
                "order": {
                    "type": "integer",
                    "description": "Order of significance of the rules, lower values mean higher priorities. This may be used to indicate the ranking of qualified competitors from previous rounds. Rules may be applied in the order specified by this argument."
                },
                "source": {
                    "type": "string",
                    "description": "Reference to a phase or unit with that code from which the competitor should be selected."
                },
                "criteria": {
                    "type": "array",
                    "description": "A list of criteria that _all_ have to apply to the competitors from source in order to proceed to the current unit.",
                    "items": { "$ref": "#/$defs/ruleCriterion" }
                },
                "qcode": {
                    "type": "string",
                    "description": "A short string/abbrevation that is used as marker for qualified competitors, e.h. 'Q' for directly qualified ones and 'q' for lucky loosers, or 'F' for competititors that reached the final(s)."
                }
            },
            "required": [ "criteria" ]
        },
        "ruleCriterion": {
            "type": "object",
            "properties": {
                "select": {
                    "type": "string",
                    "description": "The value that the value (see below) is compared with using the provided relationship (see below as well). The interpretation of that value is out of the scope of this spec."
                },
                "rel": { "enum": ["<", "<=", "=", ">=", ">", "<>"], "default": "=" },
                "value": {
                    "oneOf": [
                        { "type": "string" },
                        { "type": "number" }
                      ]
                }
            },
            "required": [ "select", "value" ]
        }
    }
}

=== christgau/sps/sports/rowing/NF/GER/AWB_4_lanes.json
{
    "title": "AWB 4 Bahnen",
    "sport": "Rowing",
    "version": "2000",
    "description": "System f√ºr Abteilungen auf 4 Bahnen",
    "capacity": 4,
    "ranges": [
        {
            "from": 2,
            "to": 4,
            "phases": [
                {
                    "label": "Finals",
                    "code": "FNL",
                    "units": [
                        { "code": "R", "label": "Hauptrennen", "rules": [] }
                    ]
                }
            ]
        },
        {
            "from": 5,
            "to": 8,
            "phases": [
                {
                    "label": "Finals",
                    "code": "FNL",
                    "units": [
                        { "code": "A1", "label": "Abteilung 1", "rules": [] },
                        { "code": "A2", "label": "Abteilung 2", "rules": [] }
                    ]
                }
            ]
        },
        {
            "from": 9,
            "to": 12,
            "phases": [
                {
                    "label": "Finals",
                    "code": "FNL",
                    "units": [
                        { "code": "A1", "label": "Abteilung 1", "rules": [] },
                        { "code": "A2", "label": "Abteilung 2", "rules": [] },
                        { "code": "A3", "label": "Abteilung 3", "rules": [] }
                    ]
                }
            ]
        },
        {
            "from": 13,
            "to": 16,
            "phases": [
                {
                    "label": "Finals",
                    "code": "FNL",
                    "units": [
                        { "code": "A1", "label": "Abteilung 1", "rules": [] },
                        { "code": "A2", "label": "Abteilung 2", "rules": [] },
                        { "code": "A3", "label": "Abteilung 3", "rules": [] },
                        { "code": "A4", "label": "Abteilung 4", "rules": [] }
                    ]
                }
            ]
        },
        {
            "from": 17,
            "to": 20,
            "phases": [
                {
                    "label": "Finals",
                    "code": "FNL",
                    "units": [
                        { "code": "A1", "label": "Abteilung 1", "rules": [] },
                        { "code": "A2", "label": "Abteilung 2", "rules": [] },
                        { "code": "A3", "label": "Abteilung 3", "rules": [] },
                        { "code": "A4", "label": "Abteilung 4", "rules": [] },
                        { "code": "A5", "label": "Abteilung 5", "rules": [] }
                    ]
                }
            ]
        },
        {
            "from": 21,
            "to": 24,
            "phases": [
                {
                    "label": "Finals",
                    "code": "FNL",
                    "units": [
                        { "code": "A1", "label": "Abteilung 1", "rules": [] },
                        { "code": "A2", "label": "Abteilung 2", "rules": [] },
                        { "code": "A3", "label": "Abteilung 3", "rules": [] },
                        { "code": "A4", "label": "Abteilung 4", "rules": [] },
                        { "code": "A5", "label": "Abteilung 5", "rules": [] },
                        { "code": "A6", "label": "Abteilung 6", "rules": [] }
                    ]
                }
            ]
        },
        {
            "from": 25,
            "to": 28,
            "phases": [
                {
                    "label": "Finals",
                    "code": "FNL",
                    "units": [
                        { "code": "A1", "label": "Abteilung 1", "rules": [] },
                        { "code": "A2", "label": "Abteilung 2", "rules": [] },
                        { "code": "A3", "label": "Abteilung 3", "rules": [] },
                        { "code": "A4", "label": "Abteilung 4", "rules": [] },
                        { "code": "A5", "label": "Abteilung 5", "rules": [] },
                        { "code": "A6", "label": "Abteilung 6", "rules": [] },
                        { "code": "A7", "label": "Abteilung 7", "rules": [] }
                    ]
                }
            ]
        },
        {
            "from": 29,
            "to": 32,
            "phases": [
                {
                    "label": "Finals",
                    "code": "FNL",
                    "units": [
                        { "code": "A1", "label": "Abteilung 1", "rules": [] },
                        { "code": "A2", "label": "Abteilung 2", "rules": [] },
                        { "code": "A3", "label": "Abteilung 3", "rules": [] },
                        { "code": "A4", "label": "Abteilung 4", "rules": [] },
                        { "code": "A5", "label": "Abteilung 5", "rules": [] },
                        { "code": "A6", "label": "Abteilung 6", "rules": [] },
                        { "code": "A7", "label": "Abteilung 7", "rules": [] },
                        { "code": "A8", "label": "Abteilung 8", "rules": [] }
                    ]
                }
            ]
        },
        {
            "from": 33,
            "to": 36,
            "phases": [
                {
                    "label": "Finals",
                    "code": "FNL",
                    "units": [
                        { "code": "A1", "label": "Abteilung 1", "rules": [] },
                        { "code": "A2", "label": "Abteilung 2", "rules": [] },
                        { "code": "A3", "label": "Abteilung 3", "rules": [] },
                        { "code": "A4", "label": "Abteilung 4", "rules": [] },
                        { "code": "A5", "label": "Abteilung 5", "rules": [] },
                        { "code": "A6", "label": "Abteilung 6", "rules": [] },
                        { "code": "A7", "label": "Abteilung 7", "rules": [] },
                        { "code": "A8", "label": "Abteilung 8", "rules": [] },
                        { "code": "A9", "label": "Abteilung 9", "rules": [] }
                    ]
                }
            ]
        },
        {
            "from": 37,
            "to": 40,
            "phases": [
                {
                    "label": "Finals",
                    "code": "FNL",
                    "units": [
                        { "code": "A1", "label": "Abteilung 1", "rules": [] },
                        { "code": "A2", "label": "Abteilung 2", "rules": [] },
                        { "code": "A3", "label": "Abteilung 3", "rules": [] },
                        { "code": "A4", "label": "Abteilung 4", "rules": [] },
                        { "code": "A5", "label": "Abteilung 5", "rules": [] },
                        { "code": "A6", "label": "Abteilung 6", "rules": [] },
                        { "code": "A7", "label": "Abteilung 7", "rules": [] },
                        { "code": "A8", "label": "Abteilung 8", "rules": [] },
                        { "code": "A9", "label": "Abteilung 9", "rules": [] },
                        { "code": "A10", "label": "Abteilung 10", "rules": [] }
                    ]
                }
            ]
        }
    ]
}

=== christgau/sps/sports/rowing/NF/GER/timetrial_all_in_one.json
{
    "title": "Langstrecke",
    "sport": "Rowing",
    "description": "System f√ºr Langstreckenrennen. Alle Boote (auch ein einzelnes) starten in einem Final-/Hauptrennen",
    "version": "1.0",
    "ranges": [
        {
            "from": 1,
            "phases": [
                {
                    "label": "Finals",
                    "code": "FNL",
                    "units": [
                        { "code": "R", "label": "Hauptrennen" }
                    ]
                }
            ]
        }
    ]
}

=== christgau/sps/sports/rowing/NF/GER/AWB_3_lanes_heats.json
{
    "title": "AWB 3 Bahnen, Vorläufe",
    "sport": "Rowing",
    "version": "2000",
    "description": "System für Rennen auf 3 Bahnen mit Vorläufen und direkter Qualifikation für ein Finale (RWR Anhang A)",
    "capacity": 3,
    "ranges": [
        {
            "from": 2,
            "to": 3,
            "phases": [
                {
                    "label": "Finals",
                    "code": "FNL",
                    "units": [
                        { "code": "R", "label": "Hauptrennen", "rules": [] }
                    ]
                }
            ]
        },
        {
            "from": 4,
            "to": 4,
            "phases": [
                {
                    "label": "Vorläufe",
                    "code": "HEAT",
                    "units": [
                        { "code": "V1", "label": "Vorlauf 1", "ruleTexts": { "short": "1 -> F" }, "rules": [] },
                        { "code": "V2", "label": "Vorlauf 2", "ruleTexts": { "short": "1 -> F" }, "rules": [] }
                    ]
                },
                {
                    "label": "Finals",
                    "code": "FNL",
                    "units": [
                        { "code": "F", "label": "Finale", "rules": [
                                { "option": 1, "order": 1, "source": "V1", "criteria": [    { "select": "rank", "value": 1 } ] },
                                { "option": 1, "order": 2, "source": "V2", "criteria": [    { "select": "rank", "value": 1 } ] }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "from": 5,
            "to": 5,
            "phases": [
                {
                    "label": "Vorläufe",
                    "code": "HEAT",
                    "units": [
                        { "code": "V1", "label": "Vorlauf 1", "ruleTexts": { "short": "1-2 -> F" }, "rules": [] },
                        { "code": "V2", "label": "Vorlauf 2", "ruleTexts": { "short": "1 -> F" }, "rules": [] }
                    ]
                },
                {
                    "label": "Finals",
                    "code": "FNL",
                    "units": [
                        { "code": "F", "label": "Finale", "rules": [
                                { "option": 1, "order": 1, "source": "V1", "criteria": [    { "select": "rank", "value": 1 } ] },
                                { "option": 1, "order": 2, "source": "V2", "criteria": [    { "select": "rank", "value": 1 } ] },
                                { "option": 1, "order": 3, "source": "V1", "criteria": [    { "select": "rank", "value": 2 } ] }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "from": 6,
            "to": 9,
            "phases": [
                {
                    "label": "Vorläufe",
                    "code": "HEAT",
                    "units": [
                        { "code": "V1", "label": "Vorlauf 1", "ruleTexts": { "short": "1 -> F" }, "rules": [] },
                        { "code": "V2", "label": "Vorlauf 2", "ruleTexts": { "short": "1 -> F" }, "rules": [] },
                        { "code": "V3", "label": "Vorlauf 3", "ruleTexts": { "short": "1 -> F" }, "rules": [] }
                    ]
                },
                {
                    "label": "Finals",
                    "code": "FNL",
                    "units": [
                        { "code": "F", "label": "Finale", "rules": [
                                { "option": 1, "order": 1, "source": "V1", "criteria": [    { "select": "rank", "value": 1 } ] },
                                { "option": 1, "order": 2, "source": "V2", "criteria": [    { "select": "rank", "value": 1 } ] },
                                { "option": 1, "order": 3, "source": "V3", "criteria": [    { "select": "rank", "value": 1 } ] }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== christgau/sps/sports/rowing/NF/GER/Championships_SN.json
{
    "title": "Landesmeisterschaften Sachsen",
    "sport": "Rowing",
    "version": "2014",
    "description": "Ausscheidungssystem für die Landesmeisterschaften Sachsen. Direkte Qualifikation vom Vorlauf zum Finale, Finale B ab 10 Booten",
    "capacity": 6,
    "ranges": [
        {
        "from": 2,
        "to": 6,
        "phases": [
            {
            "label": "Finals",
            "code": "FNL",
            "units": [
                { "code": "F", "label": "Finale", "rules": [] }
            ]
            }
        ]
        },
        {
        "from": 7,
        "to": 7,
        "phases": [
            {
            "label": "Vorläufe",
            "code": "HEAT",
            "units": [
                { "code": "V1", "label": "Vorlauf 1", "ruleTexts": { "short": "1-3 -> F" }, "rules": [] },
                { "code": "V2", "label": "Vorlauf 2", "ruleTexts": { "short": "1-2 -> F" }, "rules": [] }
            ]
            },
            {
            "label": "Finals",
            "code": "FNL",
            "units": [
                { "code": "F", "label": "Finale", "rules": [
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 1 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 1 } ] },
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 2 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 2 } ] },
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 3 } ] }
                ]
                }
            ]
            }
        ]
        },
        {
        "from": 8,
        "to": 9,
        "phases": [
            {
            "label": "Vorläufe",
            "code": "HEAT",
            "units": [
                { "code": "V1", "label": "Vorlauf 1", "ruleTexts": { "short": "1-3 -> F" }, "rules": [] },
                { "code": "V2", "label": "Vorlauf 2", "ruleTexts": { "short": "1-3 -> F" }, "rules": [] }
            ]
            },
            {
            "label": "Finals",
            "code": "FNL",
            "units": [
                { "code": "F", "label": "Finale", "rules": [
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 1 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 1 } ] },
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 2 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 2 } ] },
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 3 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 3 } ] }
                ]
                }
            ]
            }
        ]
        },
        {
        "from": 10,
        "to": 12,
        "phases": [
            {
            "label": "Vorläufe",
            "code": "HEAT",
            "units": [
                { "code": "V1", "label": "Vorlauf 1", "ruleTexts": { "short": "1-3 -> FA, 4-.. -> FB" }, "rules": [] },
                { "code": "V2", "label": "Vorlauf 2", "ruleTexts": { "short": "1-3 -> FA, 4-.. -> FB" }, "rules": [] }
            ]
            },
            {
            "label": "Finals",
            "code": "FNL",
            "units": [
                { "code": "FA", "label": "Finale", "rules": [
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 1 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 1 } ] },
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 2 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 2 } ] },
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 3 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 3 } ] }
                ]
                },
                { "code": "FB", "label": "Finale", "rules": [
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 4 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 4 } ] },
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 5 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 5 } ] },
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 6 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 6 } ] }
                ]
                }
            ]
            }
        ]
        },
        {
        "from": 13,
        "to": 18,
        "phases": [
            {
            "label": "Vorläufe",
            "code": "HEAT",
            "units": [
                { "code": "V1", "label": "Vorlauf 1", "ruleTexts": { "short": "1-2 -> FA, 3-.. -> FB" }, "rules": [] },
                { "code": "V2", "label": "Vorlauf 2", "ruleTexts": { "short": "1-2 -> FA, 3-.. -> FB" }, "rules": [] },
                { "code": "V3", "label": "Vorlauf 3", "ruleTexts": { "short": "1-2 -> FA, 3-.. -> FB" }, "rules": [] }
            ]
            },
            {
            "label": "Finals",
            "code": "FNL",
            "units": [
                { "code": "FA", "label": "Finale A", "rules": [
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 1 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 1 } ] },
                    { "source": "V3", "criteria": [ { "select": "rank", "value": 1 } ] },
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 2 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 2 } ] },
                    { "source": "V3", "criteria": [ { "select": "rank", "value": 2 } ] }
                ]
                },
                { "code": "FB", "label": "Finale B", "rules": [
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 4 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 4 } ] },
                    { "source": "V3", "criteria": [ { "select": "rank", "value": 5 } ] },
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 5 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 6 } ] },
                    { "source": "V3", "criteria": [ { "select": "rank", "value": 6 } ] }
                ]
                }
                ]
            }
        ]
        },
        {
        "from": 19,
        "to": 24,
        "phases": [
            {
            "label": "Vorläufe",
            "code": "HEAT",
            "units": [
                { "code": "V1", "label": "Vorlauf 1", "ruleTexts": { "short": "1-2 -> FA, 3-4 -> FB" }, "rules": [] },
                { "code": "V2", "label": "Vorlauf 2", "ruleTexts": { "short": "1-2 -> FA, 3-4 -> FB" }, "rules": [] },
                { "code": "V3", "label": "Vorlauf 3", "ruleTexts": { "short": "1-2 -> FA, 3-4 -> FB" }, "rules": [] }
            ]
            },
            {
            "label": "Finals",
            "code": "FNL",
            "units": [
                { "code": "FA", "label": "Finale A", "rules": [
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 1 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 1 } ] },
                    { "source": "V3", "criteria": [ { "select": "rank", "value": 2 } ] },
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 2 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 3 } ] },
                    { "source": "V3", "criteria": [ { "select": "rank", "value": 3 } ] }
                ]
                },
                { "code": "FB", "label": "Finale B", "rules": [
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 4 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 4 } ] },
                    { "source": "V3", "criteria": [ { "select": "rank", "value": 5 } ] },
                    { "source": "V1", "criteria": [ { "select": "rank", "value": 5 } ] },
                    { "source": "V2", "criteria": [ { "select": "rank", "value": 6 } ] },
                    { "source": "V3", "criteria": [ { "select": "rank", "value": 6 } ] }
                ]
                }
            ]
            }
        ]
        }
    ]
}
